---
# handlers/main.yml for mcp_obsidian role

- name: restart mcp obsidian
  community.docker.docker_compose_v2:
    project_src: "{{ mcp_obsidian_dir }}"
    files:
      - docker-compose.mcp-obsidian.yml
    state: restarted
  become: true
  become_user: "{{ mcp_owner }}"
  listen: "restart mcp obsidian"

- name: reload systemd user
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user
  become: true
  become_user: "{{ mcp_owner }}"
  listen: "reload systemd user"
